USE CSE_3A_152

--PART A--
--QUESTION1--
SELECT * FROM DEPOSIT

--QUESTION2--
SELECT * FROM BORROW

--QUESTION3--
SELECT * FROM CUSTOMERS

--QUESTION4--
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT

--QUESTION5--
SELECT LOANNO,AMOUNT FROM BORROW

--QUESTION6--
SELECT * FROM BORROW  WHERE BNAME='ANDHERI'
--QUESTION7--
SELECT ACTNO,AMOUNT FROM DEPOSIT WHERE ACTNO=106

--QUESTION8--
SELECT CNAME FROM BORROW WHERE AMOUNT>5000

--QUESTION9--
SELECT * FROM DEPOSIT WHERE ADATE>'1996-12-1'

--QUESTION10--
SELECT CNAME FROM DEPOSIT WHERE ACTNO>105

--QUESTION11--
SELECT CNAME FROM CUSTOMERS WHERE CITY='NAGPUR' OR CITY='DELHI'

SELECT CNAME FROM CUSTOMERS WHERE CITY IN('NAGPUR','DELHI')


--QUESTION12--
SELECT CNAME,BNAME FROM DEPOSIT WHERE AMOUNT>4000 AND ACTNO>105



--QUESTION13--
SELECT CNAME FROM BORROW WHERE AMOUNT>=3000 AND AMOUNT<8000

--QUESTION14--
SELECT CNAME FROM DEPOSIT WHERE  NOT BNAME='ANDHERI'

--QUESTION15--
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT WHERE BNAME IN ('AJNI','KAROLBAGH','M.G.ROAD')AND ACTNO<104 

--PARTB--
--QUESTION1--
SELECT TOP 5 * FROM CUSTOMERS

--QUESTION2--
SELECT TOP 3 * FROM DEPOSIT WHERE AMOUNT>1000

--QUESTION3--
SELECT  TOP 5 LOANNO,CNAME FROM BORROW WHERE NOT BNAME='ANDHERI'

--QUESTION4--
SELECT DISTINCT CITY FROM CUSTOMERS

--QUESTION5--
SELECT DISTINCT BNAME FROM BRANCH

--PARTC--
--QUESTION1--
SELECT TOP 50 PERCENT * FROM BORROW

--QUESTION2--
SELECT TOP 10 PERCENT * FROM DEPOSIT

--QUESTION3--
SELECT TOP 25 PERCENT * FROM DEPOSIT WHERE AMOUNT>5000

--QUESTION4--
SELECT TOP 10 PERCENT AMOUNT FROM BORROW

--QUESTION5--
SELECT DISTINCT CNAME,CITY FROM CUSTOMERS

--QUESTION6--
SELECT *,(AMOUNT+AMOUNT*0.1)AS EXTRAAMOUNT FROM BORROW

--QUESTION7--
SELECT * FROM BORROW WHERE LOANNO%2=1
SELECT * FROM BORROW WHERE LOANNO%2=0

